### ISSUE TITLE
`tfnotify` support custom environment variable

### ISSUE THREAD

**Issue by KeisukeYamashita** [mercari/tfnotify#111]
## WHAT

Curretly, to read the GitHub Token from the environment variable, the  `$GITHUB_TOKEN` is supported. It lookups the env var named `GITHUB_TOKEN` for the tokens.

https://github.com/mercari/tfnotify/blob/fb178d8a5a51f88a51b7fda93ed5443ff56dfc8f/notifier/github/client.go#L73-L75

But it would be nice if the `tfnotify` can support custom variables as below:

```yaml
ci: circleci
notifier:
  github:
    token: $MY_CUSTOM_GITHUB_TOKEN
    repository:
      owner: "mercari"
....
```

Note that this will not break existing users. The users that configure `$GITHUB_TOKEN` can still use the `GITHUB_TOKEN`  env var on their runtime.
