### ISSUE TITLE
fail go get current master HEAD ( b8bbe9b )

### ISSUE THREAD

**Issue by ziguzagu** [mercari/tfnotify#54]
## WHAT

I use tfnotify installed by `go get` on circleci like this:

``` yaml
commands:
  tfnotify:
    parameters:
      tf_type:
        type: string
    steps:
      - run:
          name: install tfnotify
          command: go get -u github.com/mercari/tfnotify
      - run:
          name: notify
          command: |
            for file in `ls -1 << parameters.tf_type >>.*`
            do
                cat ${file} | tfnotify << parameters.tf_type >> --title "## ${file} result"
            done
```

and the result of `install tfnotify` step now (2019-11-15T11:51:04+0900) bellows:

```
#!/bin/bash -eo pipefail
go get -u github.com/mercari/tfnotify
# github.com/mercari/tfnotify
/go/src/github.com/mercari/tfnotify/main.go:35:14: t.context.GlobalString undefined (type *cli.Context has no field or method GlobalString)
/go/src/github.com/mercari/tfnotify/main.go:36:21: t.context.GlobalString undefined (type *cli.Context has no field or method GlobalString)
/go/src/github.com/mercari/tfnotify/main.go:84:14: t.context.GlobalString undefined (type *cli.Context has no field or method GlobalString)
/go/src/github.com/mercari/tfnotify/main.go:85:31: t.context.GlobalString undefined (type *cli.Context has no field or method GlobalString)
/go/src/github.com/mercari/tfnotify/main.go:162:64: t.context.GlobalString undefined (type *cli.Context has no field or method GlobalString)
/go/src/github.com/mercari/tfnotify/main.go:178:17: cannot use cli.StringFlag literal (type cli.StringFlag) as type cli.Flag in array or slice literal:
	cli.StringFlag does not implement cli.Flag (Apply method has pointer receiver)
/go/src/github.com/mercari/tfnotify/main.go:179:17: cannot use cli.StringFlag literal (type cli.StringFlag) as type cli.Flag in array or slice literal:
	cli.StringFlag does not implement cli.Flag (Apply method has pointer receiver)
/go/src/github.com/mercari/tfnotify/main.go:180:17: cannot use cli.StringFlag literal (type cli.StringFlag) as type cli.Flag in array or slice literal:
	cli.StringFlag does not implement cli.Flag (Apply method has pointer receiver)
/go/src/github.com/mercari/tfnotify/main.go:188:19: cannot use cli.StringFlag literal (type cli.StringFlag) as type cli.Flag in array or slice literal:
	cli.StringFlag does not implement cli.Flag (Apply method has pointer receiver)
/go/src/github.com/mercari/tfnotify/main.go:192:19: cannot use cli.StringFlag literal (type cli.StringFlag) as type cli.Flag in array or slice literal:
	cli.StringFlag does not implement cli.Flag (Apply method has pointer receiver)
/go/src/github.com/mercari/tfnotify/main.go:192:19: too many errors
Exited with code 2
CircleCI received exit code 2
```

However, v0.3.3 looks no problems.
